use usbd_human_interface_device::page::Keyboard;
use crate::evdev::Key;
use crate::InputState;

pub fn map_key(state: &mut InputState, k: Key, value: i32) -> bool {
    if value == 0 || value == 1 { // Ignore key repeats (value 2)
        let pressed = value == 1;

        let mut set_mouse_button = |button: usize| state.mouse.set_button(button, pressed);
        let mut set_keyboard_button = |key: Keyboard| state.keyboard.set_key(key, pressed);

        match k {
            // Mouse
            Key::BTN_LEFT => set_mouse_button(0),
            Key::BTN_RIGHT => set_mouse_button(1),
            Key::BTN_MIDDLE => set_mouse_button(2),
            Key::BTN_SIDE => set_mouse_button(3),
            Key::BTN_EXTRA => set_mouse_button(4),
            Key::BTN_6 => set_mouse_button(5),
            Key::BTN_7 => set_mouse_button(6),
            Key::BTN_8 => set_mouse_button(7),

            // Keyboard
            Key::KEY_A => set_keyboard_button(Keyboard::A),
            Key::KEY_B => set_keyboard_button(Keyboard::B),
            Key::KEY_C => set_keyboard_button(Keyboard::C),
            Key::KEY_D => set_keyboard_button(Keyboard::D),
            Key::KEY_E => set_keyboard_button(Keyboard::E),
            Key::KEY_F => set_keyboard_button(Keyboard::F),
            Key::KEY_G => set_keyboard_button(Keyboard::G),
            Key::KEY_H => set_keyboard_button(Keyboard::H),
            Key::KEY_I => set_keyboard_button(Keyboard::I),
            Key::KEY_J => set_keyboard_button(Keyboard::J),
            Key::KEY_K => set_keyboard_button(Keyboard::K),
            Key::KEY_L => set_keyboard_button(Keyboard::L),
            Key::KEY_M => set_keyboard_button(Keyboard::M),
            Key::KEY_N => set_keyboard_button(Keyboard::N),
            Key::KEY_O => set_keyboard_button(Keyboard::O),
            Key::KEY_P => set_keyboard_button(Keyboard::P),
            Key::KEY_Q => set_keyboard_button(Keyboard::Q),
            Key::KEY_R => set_keyboard_button(Keyboard::R),
            Key::KEY_S => set_keyboard_button(Keyboard::S),
            Key::KEY_T => set_keyboard_button(Keyboard::T),
            Key::KEY_U => set_keyboard_button(Keyboard::U),
            Key::KEY_V => set_keyboard_button(Keyboard::V),
            Key::KEY_W => set_keyboard_button(Keyboard::W),
            Key::KEY_X => set_keyboard_button(Keyboard::X),
            Key::KEY_Y => set_keyboard_button(Keyboard::Y),
            Key::KEY_Z => set_keyboard_button(Keyboard::Z),
            Key::KEY_1 => set_keyboard_button(Keyboard::Keyboard1),
            Key::KEY_2 => set_keyboard_button(Keyboard::Keyboard2),
            Key::KEY_3 => set_keyboard_button(Keyboard::Keyboard3),
            Key::KEY_4 => set_keyboard_button(Keyboard::Keyboard4),
            Key::KEY_5 => set_keyboard_button(Keyboard::Keyboard5),
            Key::KEY_6 => set_keyboard_button(Keyboard::Keyboard6),
            Key::KEY_7 => set_keyboard_button(Keyboard::Keyboard7),
            Key::KEY_8 => set_keyboard_button(Keyboard::Keyboard8),
            Key::KEY_9 => set_keyboard_button(Keyboard::Keyboard9),
            Key::KEY_0 => set_keyboard_button(Keyboard::Keyboard0),
            Key::KEY_ENTER => set_keyboard_button(Keyboard::ReturnEnter), // TODO ?
            Key::KEY_ESC => set_keyboard_button(Keyboard::Escape),
            Key::KEY_BACKSPACE => set_keyboard_button(Keyboard::DeleteBackspace),
            Key::KEY_TAB => set_keyboard_button(Keyboard::Tab),
            Key::KEY_SPACE => set_keyboard_button(Keyboard::Space),
            Key::KEY_MINUS => set_keyboard_button(Keyboard::Minus),
            Key::KEY_EQUAL => set_keyboard_button(Keyboard::Equal),
            Key::KEY_LEFTBRACE => set_keyboard_button(Keyboard::LeftBrace),
            Key::KEY_RIGHTBRACE => set_keyboard_button(Keyboard::RightBrace),
            Key::KEY_BACKSLASH => set_keyboard_button(Keyboard::Backslash),
            // ??? => set_keyboard_button(Keyboard::NonUSHash), // TODO ?
            Key::KEY_SEMICOLON => set_keyboard_button(Keyboard::Semicolon),
            Key::KEY_APOSTROPHE => set_keyboard_button(Keyboard::Apostrophe),
            Key::KEY_GRAVE => set_keyboard_button(Keyboard::Grave),
            Key::KEY_COMMA => set_keyboard_button(Keyboard::Comma),
            Key::KEY_DOT => set_keyboard_button(Keyboard::Dot),
            Key::KEY_SLASH => set_keyboard_button(Keyboard::ForwardSlash),
            Key::KEY_CAPSLOCK => set_keyboard_button(Keyboard::CapsLock), // TODO ?
            Key::KEY_F1 => set_keyboard_button(Keyboard::F1),
            Key::KEY_F2 => set_keyboard_button(Keyboard::F2),
            Key::KEY_F3 => set_keyboard_button(Keyboard::F3),
            Key::KEY_F4 => set_keyboard_button(Keyboard::F4),
            Key::KEY_F5 => set_keyboard_button(Keyboard::F5),
            Key::KEY_F6 => set_keyboard_button(Keyboard::F6),
            Key::KEY_F7 => set_keyboard_button(Keyboard::F7),
            Key::KEY_F8 => set_keyboard_button(Keyboard::F8),
            Key::KEY_F9 => set_keyboard_button(Keyboard::F9),
            Key::KEY_F10 => set_keyboard_button(Keyboard::F10),
            Key::KEY_F11 => set_keyboard_button(Keyboard::F11),
            Key::KEY_F12 => set_keyboard_button(Keyboard::F12),
            // ??? => set_keyboard_button(Keyboard::PrintScreen), // TODO ?
            Key::KEY_SCROLLLOCK => set_keyboard_button(Keyboard::ScrollLock), // TODO ?
            Key::KEY_PAUSE => set_keyboard_button(Keyboard::Pause),
            Key::KEY_INSERT => set_keyboard_button(Keyboard::Insert),
            Key::KEY_HOME => set_keyboard_button(Keyboard::Home),
            Key::KEY_PAGEUP => set_keyboard_button(Keyboard::PageUp),
            Key::KEY_DELETE => set_keyboard_button(Keyboard::DeleteForward),
            Key::KEY_END => set_keyboard_button(Keyboard::End),
            Key::KEY_PAGEDOWN => set_keyboard_button(Keyboard::PageDown),
            Key::KEY_RIGHT => set_keyboard_button(Keyboard::RightArrow),
            Key::KEY_LEFT => set_keyboard_button(Keyboard::LeftArrow),
            Key::KEY_DOWN => set_keyboard_button(Keyboard::DownArrow),
            Key::KEY_UP => set_keyboard_button(Keyboard::UpArrow),
            Key::KEY_NUMLOCK => set_keyboard_button(Keyboard::KeypadNumLockAndClear), // TODO ?
            Key::KEY_KPSLASH => set_keyboard_button(Keyboard::KeypadDivide),
            Key::KEY_KPASTERISK => set_keyboard_button(Keyboard::KeypadMultiply),
            Key::KEY_KPMINUS => set_keyboard_button(Keyboard::KeypadSubtract),
            Key::KEY_KPPLUS => set_keyboard_button(Keyboard::KeypadAdd),
            Key::KEY_KPENTER => set_keyboard_button(Keyboard::KeypadEnter),
            Key::KEY_KP1 => set_keyboard_button(Keyboard::Keypad1),
            Key::KEY_KP2 => set_keyboard_button(Keyboard::Keypad2),
            Key::KEY_KP3 => set_keyboard_button(Keyboard::Keypad3),
            Key::KEY_KP4 => set_keyboard_button(Keyboard::Keypad4),
            Key::KEY_KP5 => set_keyboard_button(Keyboard::Keypad5),
            Key::KEY_KP6 => set_keyboard_button(Keyboard::Keypad6),
            Key::KEY_KP7 => set_keyboard_button(Keyboard::Keypad7),
            Key::KEY_KP8 => set_keyboard_button(Keyboard::Keypad8),
            Key::KEY_KP9 => set_keyboard_button(Keyboard::Keypad9),
            Key::KEY_KP0 => set_keyboard_button(Keyboard::Keypad0),
            Key::KEY_KPDOT => set_keyboard_button(Keyboard::KeypadDot),
            // ??? => set_keyboard_button(Keyboard::NonUSBackslash), // TODO ?
            Key::KEY_APPSELECT | Key::KEY_COMPOSE => set_keyboard_button(Keyboard::Application),
            Key::KEY_POWER => set_keyboard_button(Keyboard::Power),
            Key::KEY_KPEQUAL => set_keyboard_button(Keyboard::KeypadEqual),
            Key::KEY_F13 => set_keyboard_button(Keyboard::F13),
            Key::KEY_F14 => set_keyboard_button(Keyboard::F14),
            Key::KEY_F15 => set_keyboard_button(Keyboard::F15),
            Key::KEY_F16 => set_keyboard_button(Keyboard::F16),
            Key::KEY_F17 => set_keyboard_button(Keyboard::F17),
            Key::KEY_F18 => set_keyboard_button(Keyboard::F18),
            Key::KEY_F19 => set_keyboard_button(Keyboard::F19),
            Key::KEY_F20 => set_keyboard_button(Keyboard::F20),
            Key::KEY_F21 => set_keyboard_button(Keyboard::F21),
            Key::KEY_F22 => set_keyboard_button(Keyboard::F22),
            Key::KEY_F23 => set_keyboard_button(Keyboard::F23),
            Key::KEY_F24 => set_keyboard_button(Keyboard::F24),
            // ??? => set_keyboard_button(Keyboard::Execute), // TODO ?
            Key::KEY_HELP => set_keyboard_button(Keyboard::Help),
            Key::KEY_MENU => set_keyboard_button(Keyboard::Menu),
            Key::KEY_SELECT => set_keyboard_button(Keyboard::Select),
            Key::KEY_STOP => set_keyboard_button(Keyboard::Stop),
            Key::KEY_AGAIN => set_keyboard_button(Keyboard::Again),
            Key::KEY_UNDO => set_keyboard_button(Keyboard::Undo),
            Key::KEY_CUT => set_keyboard_button(Keyboard::Cut),
            Key::KEY_COPY => set_keyboard_button(Keyboard::Copy),
            Key::KEY_PASTE => set_keyboard_button(Keyboard::Paste),
            Key::KEY_FIND => set_keyboard_button(Keyboard::Find),
            Key::KEY_MUTE => set_keyboard_button(Keyboard::Mute),
            Key::KEY_VOLUMEUP => set_keyboard_button(Keyboard::VolumeUp),
            Key::KEY_VOLUMEDOWN => set_keyboard_button(Keyboard::VolumeDown),
            // ??? => set_keyboard_button(Keyboard::LockingCapsLock), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LockingNumLock), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LockingScrollLock), // TODO ?
            Key::KEY_KPCOMMA => set_keyboard_button(Keyboard::KeypadComma),
            // ??? => set_keyboard_button(Keyboard::KeypadEqualSign), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji1), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji2), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji3), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji4), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji5), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji6), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji7), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji8), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Kanji9), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG1), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG2), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG3), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG4), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG5), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG6), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG7), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG8), // TODO ?
            // ??? => set_keyboard_button(Keyboard::LANG9), // TODO ?
            Key::KEY_ALTERASE => set_keyboard_button(Keyboard::AlternateErase),
            // Key::KEY_SYSRQ => set_keyboard_button(Keyboard::SysReqAttention), // TODO Interestingly, SysRq only maps properly to PrintScreen, otherwise it does not generate any events
            Key::KEY_SYSRQ => set_keyboard_button(Keyboard::PrintScreen),
            Key::KEY_CANCEL => set_keyboard_button(Keyboard::Cancel),
            Key::KEY_CLEAR => set_keyboard_button(Keyboard::Clear),
            // ??? => set_keyboard_button(Keyboard::Prior), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Return), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Separator), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Out), // TODO ?
            // ??? => set_keyboard_button(Keyboard::Oper), // TODO ?
            // ??? => set_keyboard_button(Keyboard::ClearAgain), // TODO ?
            // ??? => set_keyboard_button(Keyboard::CrSelProps), // TODO ?
            // ??? => set_keyboard_button(Keyboard::ExSel), // TODO ?
            Key::KEY_LEFTCTRL => set_keyboard_button(Keyboard::LeftControl),
            Key::KEY_LEFTSHIFT => set_keyboard_button(Keyboard::LeftShift),
            Key::KEY_LEFTALT => set_keyboard_button(Keyboard::LeftAlt),
            Key::KEY_LEFTMETA => set_keyboard_button(Keyboard::LeftGUI),
            Key::KEY_RIGHTCTRL => set_keyboard_button(Keyboard::RightControl),
            Key::KEY_RIGHTSHIFT => set_keyboard_button(Keyboard::RightShift),
            Key::KEY_RIGHTALT => set_keyboard_button(Keyboard::RightAlt),
            Key::KEY_RIGHTMETA => set_keyboard_button(Keyboard::RightGUI),
            _ => return false
        }
    }

    return true
}